### PR TITLE
Add scrolling game camera

### LINKED ISSUE #22: Viewport
# User Story
As a player
I want to only see the "important" things of the game

# Description
- viewport to crop the game and make only a view plattforms visible
- if I don't do this the player would always see the whole game and the player would be way to tiny

# Material
- tilemap camera / moving background
- scrolling camera

### PR DESCRIPTION
**Pull request by JoscaWij**
Fixes #22 Viewport

✅ player only sees part of the game

I decided to go for a **scrolling camera** known from games **like flappy bird**. I think this is the quickest way to implement a camera in my game just now - and not rewrite the whole movement code and instead move the background. So here is what I came up with. 

deployment: https://spacey-gamecamera-zf34hplu73y5.herokuapp.com
storybook: https://spacey-gamecamera-zf34hplu73y5.herokuapp.com/storybook/?path=/story/game-camera--game-inkl-camera

_Happy Gaming_ 👩‍🚀 🌚 🚀 

❕ canvas size and placement of the platform, player and floor will be changed later anyway, but I had to place them at the bottom of the canvas and make the canvas longer to try this out 😇 So **placement can be ignored** [**platforms.js, draw.js, GameLoop.js, Game.js**]

_coming up:_
⏭️ player death when he isn't fast enough
⏭️ player can't leave the canvas at the left and right side

Alternative to #50 (💀 that totally didn't work 😅 useEffect and a dozen rerenders - totally crashed the game. But I had to try 🤓 😥😅)

### CODE REVIEW

**Review by manuelsanchez2 — APPROVED** [review]
Really good job! Surely you have been thinking about it, but it would be awesome to have a platform generator than randomly creates the platforms in a way!

**Comment by j-toscani** [comment]
Hey Josca, what happens if the user is faster than the plattforms? Are there already new platforms or do you plan on making the camera go faster?

I dont know if `player can't leave the canvas at the left and right side` is really necessary. This yould be another level of complexity for your game! Cheers!

**Review by lmachens — APPROVED** [review]
Good job!

**Comment by JoscaWij** [comment]
@j-toscani
> Hey Josca, what happens if the user is faster than the plattforms? Are there already new platforms or do you plan on making the camera go faster?

unfortunatly the camera is hard coded and can't get faster :/ I tried to implement a flexible camera, but that crashed the game completely. I will look at this when bootcamp is over ;) 

> I dont know if `player can't leave the canvas at the left and right side` is really necessary. This yould be another level of complexity for your game! Cheers!

didn't decide about this one yet. But now the player just disappears into nothing when leaving the canvas.


Thanks for your input 😸

**Pull request merged**
